@baseUrl = http://localhost:3000

### Checkout - success
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "userName": "Guilherme",
  "email": "gui@fullcycle.com.br",
  "password": "senhaforte",
  "courseId": 2,
  "cardNumber": "4111222233334444"
}

### Checkout - payment denied
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "userName": "João",
  "email": "joao@teste.com",
  "password": "123",
  "courseId": 1,
  "cardNumber": "5111222233334444"
}

### Financial report (admin)
GET {{baseUrl}}/api/admin/financial-report

### Delete user
DELETE {{baseUrl}}/api/users/1
